version: "3.8"

services:
  travelog:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - travelog:/var/lib/postgresql/data/

  travelog-test:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - travelog-test:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  travelog:
  travelog-test:
  pgadmin:
